DTC_INCLUDE += $(srctree)/../qcs8550-modules/qcom/opensource/audio-kernel/include

dtbo-$(CONFIG_ARCH_KALAMA) += ../../qcom/audio/kalama-audio.dtbo \
		kalama-audio-ayn-odin2.dtbo \
		kalama-audio-ayn-odin2-mini.dtbo \
		kalama-audio-ayn-odin2-portal.dtbo \
		kalama-audio-ayn-odin2-thor.dtbo \
		kalama-audio-retroid-pocket-6.dtbo \
		kalama-audio-retroid-pocket-nova.dtbo

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
